<a href="https://colab.research.google.com/github/yantitheresia/STKI-2023/blob/main/YANTI_THERESIA_SIHOMBING_A11_2020_13157_REPO_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.random.seed(42)
v_revenge = np.array([2,1,3,7,5,4]) #"revenge"
print(v_revenge)
#array([3, 5, 7, 1, 4, 2])
weight = np.random.random_sample((6,3))
print(weight)
# array([[ 0.43194502,  0.29122914,  0.61185289],
#        [ 0.13949386,  0.29214465,  0.36636184],
#        [ 0.45606998,  0.78517596,  0.19967378],
#        [ 0.51423444,  0.59241457,  0.04645041],
#        [ 0.60754485,  0.17052412,  0.06505159],
#        [ 0.94888554,  0.96563203,  0.80839735]])

hidden_layer_sg = np.dot(v_revenge,weight)
print(hidden_layer_sg)
#array([ 0.45606998,  0.78517596,  0.19967378])
weight_prime = np.random.random_sample((3,6))
print(weight_prime)
#array([[ 0.30461377, 0.09767211, 0.68423303, 0.44015249, 0.12203823, 0.49517691],
       # [ 0.03438852, 0.9093204, 0.25877998, 0.66252228, 0.31171108,      0.52006802],
       # [ 0.54671028, 0.18485446, 0.96958463, 0.77513282, 0.93949894,    0.89482735]])
o_the = np.dot(hidden_layer_sg, weight_prime)
print(o_the)
#array([ 0.27508995, 0.79543243, 0.7088466, 0.87571061, 0.48799933, 0.8128538 ])

[2 1 3 7 5 4]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]
[11.37432885  7.07873168 13.22084697]
[[0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]]
[16.17373924 11.1250593   9.23289031 17.77184713 20.28296641 15.18362772]


In [3]:
v_the = np.array([1,0,1,0,1,0]) #"the"
print(v_the)
#array([1, 0, 1, 0, 0, 1])
#weight = menggunakan weight yang sama dengan ilustrasi pada Skip-Gram
hidden_layer_cbow = np.dot(v_the,weight)
print(hidden_layer_cbow)
#array([0.43194502, 0.29122914, 0.61185289])
#weight_prime = menggunakan weight_prime yang sama dengan ilustrasi pada Skip-Gram
o_revenge = np.dot(hidden_layer_cbow, weight_prime)
print(o_revenge)
#array([0.47609761, 0.42011332, 0.96415848, 0.85733473, 0.7183283, 0.91285087])

[1 0 1 0 1 0]
[1.26506637 2.02922956 1.51493392]
[2.39230012 2.22005924 1.27776733 2.6574676  3.03459625 1.78239916]
